### ISSUE TITLE
Ensure that Span Data Conventions is up to date

### ISSUE THREAD

**Issue by Zylphrex** [getsentry/sentry-conventions#12]
With EAP coming up, we need to ensure we correctly expose any fields in span data as one of the goals is to ensure that they are properly searchable. Having this list up to date means we can make sure that if any requires special handling on in the search, we can handle it properly.

We'll need the full name of the attribute, and the type to do this.

**Comment by AbhiPrasad** [comment]
Tracking this with https://github.com/getsentry/sentry-conventions/issues/12

Made some progress here: https://github.com/getsentry/sentry-conventions/tree/main/model/trace
